### ISSUE TITLE
Reduce size of post status notices

### ISSUE THREAD

**Issue by ToksT** [danbooru/danbooru#1527]
Like this, from RaisingK's script:

``` css
/* Reduce padding around post status notices */
div#c-posts div#a-show #pool-nav, div#c-posts div#a-show #search-seq-nav, div#c-posts div#a-show #nav-help { margin: 0px 0px 0.5em 0px; }
div#c-posts div.nav-notice { padding: 0.5em; }
div#c-posts div.notice { padding: 0.5em; margin-bottom: 0.5em; }
```
