### ISSUE TITLE
Make the default starting size on desktop mode be the normal image size

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4439]
Brought up by Zurreak on Danbooru ([forum #166061](https://danbooru.donmai.us/forum_posts/166061)):
> I see. I misunderstood the question because I had been unaware of the site update. Now that I've noticed it, it really seems like the sort of thing that should be optional. Zooming in on the webpage to get a closer look at the image makes it smaller and when zooming out to get the entire image to fit on screen it's a lot harder to visually estimate how many times you need to zoom out, slowing down the process. `@BrokenEagle98` Would it be possible to add an entry into settings to natively disable this behavior (if this behavior is here to stay)?

After speaking with Zurreak through DMail to clarify the above, it seems that they would prefer that resize to window only apply automatically when in responsive move, and in desktop mode have the image start out at its normal size.

This could be done using only CSS by doing something similar to what I did on [forum #166058](https://danbooru.donmai.us/forum_posts/166058).

```css
@media screen and (max-width: 660px){
    #c-posts #a-show #image:not(.fit-width) {
        max-width: unset;
        height: unset;
    }
    #c-posts #a-show #image.fit-width {
        max-width: 100%;
        height: auto;
    }
}
@media screen and (min-width: 661px){
    #c-posts #a-show #image:not(.fit-width) {
        max-width: 100%;
        height: auto;
    }
    #c-posts #a-show #image.fit-width {
        max-width: unset;
        height: unset;
    }
}
```
