### ISSUE TITLE
HTTP Origin header didn't match request.base_url when signing up on a Danbooru instance

### ISSUE THREAD

**Issue by AxelTerizaki** [danbooru/danbooru#5524]
Hello.

I've been trying to setup a public Danbooru using the docker installation and while it works, signing up as a new user is impossible.

Once you fill the sign up form, you get the following error message 👍 

`Error: HTTP Origin header (https://xxx) didn't match request.base_url (http://xxx)`

Obviously, something in the config is thinking that the base_url is http only for some reason. I see that in the default_config.rb file in the source code : 

```ruby
    def canonical_url
      "http://#{Danbooru.config.hostname}"
    end
```

For some reason my environment variables are ignored.

Here's my docker_compose.yml

```yaml
# A Docker Compose file that launches a minimal Danbooru instance. This is
# suitable as a quick demo or for personal use, not for public-facing sites.
#
# This will start a Danbooru instance running on http://localhost:3000.
#
# Usage:
#
#  docker-compose up
#  docker-compose down
#
# References:
#
# * https://docs.docker.com/get-docker/
# * https://docs.docker.com/compose/install/
# * https://docs.docker.com/compose/compose-file/compose-versioning
# * https://docs.docker.com/compose/release-notes

# Version 3.4 is the latest version that is supported by the version of Docker
# Compose shipped with Ubuntu 18.04 LTS (version 1.17.4).
version: "3.4"

name: danbooru

x-base-template: &base-template
  user: root
  pull_policy: always # Uncomment this to always pull the latest image when deploying.
  image: ghcr.io/danbooru/danbooru:master # you can change this to danbooru:master to get the latest upstream changes
  environment:
    RAILS_ENV: production # Set this to development to force danbooru to freshly compile js/css assets (for example if you're doing local development)
    RAILS_SERVE_STATIC_FILES: true
    PUMA_WORKERS: 1
    DATABASE_URL: postgresql://danbooru@postgres/danbooru
    DANBOORU_APP_NAME: xxx
    DANBOORU_REDIS_URL: redis://redis:6379
    DANBOORU_IQDB_URL: http://iqdb:5588
    # DANBOORU_CANONICAL_URL: http://localhost:3000
    # # If you want to host danbooru under your own domain you need to replace the above line with the following (replace with your actual domain):
    DANBOORU_CANONICAL_URL: https://xxx
    DANBOORU_HOSTNAME: xxx
    DANBOORU_CONTACT_EMAIL: xxx@xxx.xxx
    DANBOORU_NEW_USER_VERFICATION: false
    DANBOORU_USER_UPGRADES_ENABLED: false

  volumes:
    - "/var/danbooru/data/images:/danbooru/public/data"
    # # If you want to do local development you can uncomment these lines to force the container to use your local changes
    # # Simply replace $HOME/danbooru to where you cloned the repo
    # - "$HOME/danbooru/app:/danbooru/app"
    # - "/var/danbooru/data/config:/danbooru/config"
    # - "$HOME/danbooru/db:/danbooru/db"
    # - "$HOME/danbooru/test:/danbooru/test"

services:
  danbooru:
    <<: *base-template
    ports:
      - "5000:3000"
    tmpfs:
      - /tmp
    depends_on:
      - postgres
    restart: always
    command: ["bash", "-c", "bin/rails db:prepare && bin/rails db:seed && bin/rails server -b 0.0.0.0"]

  cron:
    <<: *base-template
    depends_on:
      - danbooru
    command: ["bash", "-c", "bin/wait-for-http http://danbooru:3000 5s && bin/rails danbooru:cron"]

  jobs:
    <<: *base-template
    depends_on:
      - danbooru
    command: ["bash", "-c", "bin/wait-for-http http://danbooru:3000 5s && bin/good_job start"]

  # https://github.com/danbooru/iqdb
  # https://hub.docker.com/repository/docker/evazion/iqdb
  iqdb:
    image: evazion/iqdb
    volumes:
      - "/var/danbooru/data/iqdb:/iqdb/data"
    command: ["http", "0.0.0.0", "5588", "/iqdb/data/iqdb.sqlite"]

  redis:
    image: redis

  postgres:
    image: evazion/postgres
    environment:
      POSTGRES_USER: danbooru
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "/var/danbooru/data/db:/var/lib/postgresql/data"

#volumes:
#  danbooru-images:
#    name: danbooru-images
#  danbooru-data:
#    name: danbooru-data
#  iqdb-data:
#    name: iqdb-data
```

Any idea what I am missing?

Thanks in advance
